# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.calcMSSDCpp <- function(x) {
    .Call('pedometrics_calcMSSDCpp', PACKAGE = 'pedometrics', x)
}

rowMinCpp <- function(x) {
    .Call('pedometrics_rowMinCpp', PACKAGE = 'pedometrics', x)
}

.spJitterCpp <- function(x, y, xmax, xmin, ymax, ymin, idx) {
    .Call('pedometrics_spJitterCpp', PACKAGE = 'pedometrics', x, y, xmax, xmin, ymax, ymin, idx)
}

.updateMSSDCpp <- function(x1, x2, dm, idx) {
    .Call('pedometrics_updateMSSDCpp', PACKAGE = 'pedometrics', x1, x2, dm, idx)
}

.updatePPLCpp <- function(x, dm, idx) {
    .Call('pedometrics_updatePPLCpp', PACKAGE = 'pedometrics', x, dm, idx)
}

